import { createManifestHandler } from "@/lib/routes/manifest";
import { APP_DESCRIPTION, APP_ICON, APP_ID, APP_NAME, APP_VERSION } from "@/lib/app-config";

export const GET = createManifestHandler({
  id: APP_ID,
  name: APP_NAME,
  version: APP_VERSION,
  description: APP_DESCRIPTION,
  icon: APP_ICON,
  permissions: [],
  surfaceSchemaVersion: 1,
  surfaces: [
    {
      id: "sample-widget",
      kind: "widget",
      placement: "dashboard",
      name: "Sample Widget",
      description: "Starter dashboard widget",
      embedPath: "/embed/widget/sample-widget",
      permissions: [],
      defaultSize: { width: 24, height: 16 },
      minSize: { width: 16, height: 10 },
      maxSize: { width: 40, height: 32 },
    },
    {
      id: "sample-timeline-card",
      kind: "timeline-card",
      placement: "timeline",
      name: "Sample Timeline Card",
      description: "Starter timeline entry renderer",
      embedPath: "/embed/timeline/sample",
      permissions: [],
      defaultSize: { width: 48, height: 18 },
      minSize: { width: 32, height: 12 },
      maxSize: { width: 64, height: 28 },
      triggers: ["myapp.sample.created"],
    },
    {
      id: "sample-info-card",
      kind: "info-card",
      placement: "app-detail",
      name: "Sample Info Card",
      description: "Starter URL/context card renderer",
      embedPath: "/embed/card/sample",
      permissions: [],
      defaultSize: { width: 48, height: 16 },
      minSize: { width: 32, height: 12 },
      maxSize: { width: 64, height: 28 },
      triggers: ["https://example.com/*", "https://*.example.com/*"],
    },
    {
      id: "sample-notification",
      kind: "notification",
      placement: "notification-center",
      name: "Sample Notification",
      description: "Starter notification renderer",
      embedPath: "/embed/notification/default",
      permissions: [],
      defaultSize: { width: 40, height: 10 },
      minSize: { width: 32, height: 8 },
      maxSize: { width: 48, height: 18 },
    },
    {
      id: "app-settings",
      kind: "settings-panel",
      placement: "app-settings",
      name: "App Settings",
      description: "Starter settings panel",
      embedPath: "/embed/settings",
      permissions: [],
    },
  ],
});
